image: docker:latest

before_script:
  - if [[ $CI_BUILD_REF_NAME == "master" ]]; then export BUILD_FOR_ENV=prod; else  export BUILD_FOR_ENV=staging; fi

services:
  - postgres:12.3-alpine

variables:
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USERNAME: admin
  DB_PASSWORD: admin
  FACEBOOK_APP_ACCESS_TOKEN: 784845042320958|X0fC6SVCrmpr7No1r1YWhqrHigw
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  cache:
    key: "builder"
    paths:
      - ./.build
  script:
    - echo "$SECRET_KEY_BASE" > config/master.key
    - docker login  -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build  -t legaldrive/savvy-backend:$BUILD_FOR_ENV .
    - docker push   legaldrive/savvy-backend:$BUILD_FOR_ENV
  only:
    - master
    - staging
    - merge_requests

deploy_job_staging:
  stage: deploy
  image: legaldrive/savvy-backend:staging
  script:
    - "which ssh-agent || ( apk add --no-cache --update && apk install openssh)"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_STAGING")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh deploy@moveplus.dynu.net 'cd /home/deploy/docker-savvy-backend/; ./deploy-and-restart.sh staging'
  only:
    - staging
    - merge_requests

test_all_job:
  stage: test
  image: legaldrive/savvy-backend:staging
  variables:
    JRUBY_OPTS: "--debug"
  script:
    - cd /app
    - bundle install
    - rails db:create
    - rails db:migrate
    - rails test
  only:
    - master
    - staging
    - merge_requests
