version: "3"
volumes:
  bundle:
  postgresData:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - db
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    restart: always
    env_file:
      - .env.local
    volumes:
      - bundle:/usr/local/bundle
      - ./:/app
    ports:
      - 3008:3000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: "Asia/Bangkok"
    ports:
      - 5432:5432
    volumes:
      - postgresData:/var/lib/postgresql/data
